user_db_file: "userData.db"

command_responses:
  start: "Если у вас останутся вопросы - нажмите кнопу *Позвоните мне*, и наш менеджер свяжемся с вами в ближайшее время!"
  gameover: "Список игроков на ближайший \"Денежный поток\" был удален. 🗑️ "
  default: "Извините, я не знаю такой команды 😔"

query_responses:
  first_registration: "Привет!👋\nПохоже, я еще не знаком с вами.\nЧтобы участвовать в играх - нашим сотрудникам нужно знать ваш телефон, это позволит нам быстро решать организационные вопросы!☎️\nПосле нажатия\n\"*%s*\"\nповторно нажмите\n\"*%s*\"\nи вам станут доступны дополнительные пункты меню регистрации на игры -\n\"*%s*\" и \"*%s*\"."
  first_registration_owner_notification: "%s, привет!👋\nУ нас новый пользователь - @%s 🥳\n\nВсего зарегистрированных пользователей: %d"
  registration: "Привет, %s!👋\nЗапись на игры осуществлается только по предварительной оплате.\n\n\nРеквизиты 💳\n\nФИО:\t*%s*\n\nНомер карты(Сбер):\t*%s*\n\n\nДля подтверждения оплаты вам нужно отправить сюда квитанцию (в PDF-формате).🧾\nЕё можно скачать в приложении банка, откуда был осуществлен перевод.📱"
  new_phone: "Если вы укажете свой телефон - это поможет нам проще и быстрее решать организационные вопросы.🚀"
  price: "🔹 1 человек -1500₽ (если пришли с другом, то 2500₽ за двоих🔥)\n\n🔹 2-4 человека - 4000₽\n\n🔹 6-7 человек -7000₽ (отдельный игровой стол)\n\n🔹 Корпоративная игра 14-ти человек - 15000₽ (два игровых стола)\n\n🔹 Абонемент на 12 игр - 10000₽."
  pay: "TODO: описание процесса оплаты"
  change_phone: "Наш менеджер свяжется с вами в ближайшее время!☎️\nЕсли у вас изменился номер нажмите *%s*."
  set_phone: "Укажите номер, по которому мы можем связаться с вами.🆕🔥"
  thanks: "Спасибо, что помогаете нам улучшить качество сервиса.🥳"
  check_payment: "%s, привет!👋\nПользователь @%s (ID_%d) прислал квитанцию об оплате. Требуется проверить банковский счет."
  owner_confirmed_payment: "Пользователь @%s получит уведомление о том, что все отлично и он участвует в игре.🔥\nВот его номер телефона, на всякий случай: +%s"
  owner_declined_payment: "Пользователь @%s получит уведомление о том, что деньги не пришли на твой банковский счет‼️\nХорошо бы связаться с ним и прояснить ситуацию, вот номер телефона: +%s"
  player_notification: "Отлично, теперь вы участник нашей игры!🔥\n Пожалуйста, оставайтесь на связи - возможно, нам потребуется уточнить некоторые детали."
  location: "📍Каждый Вторник и Воскресение, в Антикафе РОС - мы играем в «*Денежный поток*», начало в 19.00!⏳\n\nЧто Вы получите?\n🔹Нетворкинг / новые знакомства / общение\n🔹Детальный разбор от ведущего , а также психолога\n🔹Массу открытий и инсайтов\nДинамичную Игру, отражающую реали финансового рынка 2022 года\n🔹Научитесь грамотно применять финансовый отчет в жизни\n🔹Подарок победителю🎁\n\n✅Удобное месторасположение, недалеко от метро Маяковская🚇\n✅Имеется бесплатная и платная парковка (бесплатные места ограниченны, бронируйте заранее) 🚗\n✅Опытные ведущие, которые проволят увлекательные эвенты🎤\n✅Если ты новенький - здорово, нас все учатся в процессе😅\n✅Чай, печеньки, кофе, какао - все включено☕\n\nВторник и Воскресение\nВремя: Сбор с 18.30, начало в 19.00🕖\nДлительность игры - 3 часа⏳\nСтоимость участия 1500₽ (если пришли с другом, то 2500₽ за двоих🔥)\n\n%s"
  player_call_request: "%s, привет!👋\nПользователь @%s просит позвонить ему. Вот номер телефона: +%s"
  get_rule_book: "Описание правил."

errors:
  invalid_payment_doc: "Похоже, вы отправили документ, не являющийся квитанцией об оплате. Попробуйте снова, или нажмите *%s*, и наш сотрудник свяжется с вами в ближайшее время.☎️"
  declined_payment: "К сожалению, деньги не пришли на наш банковский счет. Давайте созвонимся и уладим это недоразумение!🤝"
  not_enough_rights: "У вас недостаточно прав на выполнение этой команды! 🔒"
  already_confirmed: "Ранее, вы уже подтвердили свое участие в \"Денежном потоке\"!🤘\nПовторная отправка квитанции об оплате не требуется."

button_templates:
  registration_btn: "📝 Записаться на игру"
  location_btn: "📍 Место проведенеия игр"
  price_btn: "💰 Цены"
  pay_btn: "💳 Оплата"
  call_btn: "📲 Позвоните мне"
  main_chat_btn: "⚔️ Игровой чат"
  rules: "📕 Правила игры"
  change_phone_btn: "🔄 Изменить номер телефона"
  get_phone_btn: "📞 Указать номер телефона"
  get_location_btn: "🌎 Указать геолокацию"
  payment_doc_button: "🧾 Квитанция"
  payment_confirmed_button: "✅ Подтвердить оплату"
  payment_declined_button: "❎ Оплата не прошла"