db_file: "userData.db"

command_responses:
  start: "Если у вас останутся вопросы - нажмите кнопу *Позвоните мне*, и наш менеджер свяжемся с вами в ближайшее время!"
  default: "Извините, я не знаю такой команды 😔"

query_responses:
  cancel: "Ваша запись аннулирована. Будем рады вас видеть в другой день! 😉"
  new_phone: "Если вы укажете свой телефон - это поможет нам проще и быстрее решать организационные вопросы.🚀"
  change_phone: "Наш менеджер свяжется с вами в ближайшее время!☎️\nЕсли у вас изменился номер нажмите *%s*."
  set_phone: "Укажите номер, по которому мы можем связаться с вами.🆕🔥"
  thanks: "Спасибо, что помогаете нам улучшить качество сервиса.🥳"

button_templates:
  registration_btn: "📝 Записаться на игру"
  cancel_btn: "❌ Отменить запись"
  location_btn: "📍 Место проведенеия игр"
  price_btn: "💳 Цены и оплата"
  call_btn: "📲 Позвоните мне"
  main_chat_btn: "⚔️ Основной Чат"
  guest_chat_btn: "👋 Гостевой Чат"
  change_phone_btn: "Изменить номер телефона"
  get_phone_btn: "📞 Указать номер телефона"
  get_location_btn: "🌎 Указать геолокацию"